Homework 1
gugelius/Andersen-course pull request #1
Opened 2024-12-21 20:04 UTC by gugelius

First homework is ready for check!

2024-12-22 19:09 UTC, elnurmes requested changes

2024-12-22 19:09 UTC, elnurmes commented on src/Main.java
> +            System.out.println("User Menu:");
try to use java text blocks: https://www.baeldung.com/java-text-blocks

2024-12-22 19:09 UTC, elnurmes commented on src/Main.java
> +                        if (manager.isSpacesEmpty()) {
create separate method and use it here

2024-12-22 19:09 UTC, elnurmes commented on src/Main.java
> +                        if (manager.isSpacesEmpty()) {
same for other switches

2024-12-22 19:09 UTC, elnurmes commented
@gugelius Hi! In general good job) I left some comments, pls fix them

2024-12-24 17:42 UTC, gugelius commented
Solved problems you mentioned before, ready for check!

2024-12-24 19:14 UTC, elnurmes approved these changes
Hi! you can merge it

2024-12-24 22:18 UTC, merged